#user
USER_TYPE_RANGE = 0..1
USER_STATUS_RANGE = 0..1
USER_STATUS_BLOCKED = 0

#session
STOKEN_LENGTH = 12


#AUTH
AUTH_STATUS_RANGE = 0..2
AUTH_STATUS_NOT_CONFIRMED = 0
PASSWORD_MINIMUM_LENGTH = 8
AUTH_STATUS_CONFIRMED = 1

#VERIFICATION
VARIFICATION_STATUS_RANGE = 0..2
VERIFICATION_TYPE_CONFIRM_EMAIL = 0
VERIFICATION_PIN_LENGTH = 999999
TIME_FOR_PIN_TO_EXPIRE = 5
VERIFICATION_STATUS_VERIFIED = 1
VERIFICATION_STATUS_DELAYED = 2
VERIFICATION_TYPE_RESET = 1 # use to reset password verifications
VERIFICATION_TYPE_STANDARD = 0 #use for standard verifications


#validity 4 POSTS
Validity_RANGE = 0..2